# Generated by Django 4.1.13 on 2024-02-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.championship')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=255)),
                ('player_points', models.IntegerField()),
                ('player_team', models.CharField(max_length=255)),
                ('player_team_nickname', models.CharField(max_length=255)),
                ('player_team_code', models.CharField(max_length=10)),
                ('player_pos', models.CharField(max_length=5)),
                ('player_min', models.IntegerField()),
                ('player_fgm', models.IntegerField()),
                ('player_fga', models.IntegerField()),
                ('player_fgp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('player_ftm', models.IntegerField()),
                ('player_fta', models.IntegerField()),
                ('player_ftp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('player_tpm', models.IntegerField()),
                ('player_tpa', models.IntegerField()),
                ('player_tpp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('player_offReb', models.IntegerField()),
                ('player_defReb', models.IntegerField()),
                ('player_totReb', models.IntegerField()),
                ('player_assists', models.IntegerField()),
                ('player_pFouls', models.IntegerField()),
                ('player_steals', models.IntegerField()),
                ('player_turnovers', models.IntegerField()),
                ('player_blocks', models.IntegerField()),
                ('player_plusMinus', models.IntegerField()),
                ('game_start', models.DateTimeField()),
                ('game_status', models.CharField(max_length=20)),
                ('home_team_id', models.CharField(max_length=10)),
                ('home_team_name', models.CharField(max_length=255)),
                ('visitors_team_id', models.CharField(max_length=10)),
                ('visitors_team_name', models.CharField(max_length=255)),
                ('visitors_team_score', models.IntegerField()),
                ('home_team_score', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.player')),
            ],
        ),
        migrations.AddField(
            model_name='championship',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.sport'),
        ),
    ]
