# Generated by Django 4.1.13 on 2024-02-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_rename_name_player_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='home_team_score',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='visitors_team_score',
            field=models.CharField(max_length=2),
        ),
    ]
